services:
  api:
    build: .
    ports:
      - 6000:3000
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      PARKING_LOT_SERVICE_URL: http://host.docker.internal:4000
      USER_SERVICE_URL: http://host.docker.internal:7000
      MATCHING_SERVICE_URL: http://host.docker.internal:9000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example