services:
  api:
    build: .
    ports:
      - 6000:3000
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
      PARKING_LOT_SERVICE_URL: http://host.docker.internal:5346/parking-lots-service
      USER_SERVICE_URL: http://host.docker.internal:5346/user-service
      MATCHING_SERVICE_URL: http://host.docker.internal:5346/reservation-service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example