services:
  api:
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017